spring:
  config:
    import: aws-secretsmanager:dev/techpost/mysql
  datasource:
    url: jdbc:mysql://${host}:${port}/techpost_dev
    username: ${username}
    password: ${password}

aws:
  region: ap-northeast-2

