name: Deploy to AWS EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH Key
        run: |
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > /tmp/ec2_key.pem
          chmod 600 /tmp/ec2_key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ec2_key.pem ec2-user@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app-api:latest
            docker stop app-api || true
            docker rm app-api || true
            docker run -d --name app-api -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/app-api:latest
          EOF
