name: Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch'
        required: true
        default: master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image (app-api)
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/techpost-app-api:latest -f app-api/Dockerfile .

      - name: Push Docker Image (app-api)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/techpost-app-api:latest
