name: App Batch Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project: techpost
      module: app-batch
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      project: techpost
      module: app-batch
      port: 18020
      spring_profiles_active: prod
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
      AWS_EC2_SSH_KEY: ${{ secrets.AWS_EC2_SSH_KEY }}
