name: Build

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      module:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant permission
        run: chmod +x ${{ inputs.module }}/gradlew

      - name: Build gradle
        run: cd ${{ inputs.module }} && ./gradlew clean build

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project }}/${{ inputs.module }}:latest -f ${{ inputs.module }}/Dockerfile .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project }}/${{ inputs.module }}:latest
